# **MINI PROJECT 2**

# **Phase 1: Setup and Inspection**

## **Objective**

In this phase, we will:
- Import the required libraries.
- Load the Titanic dataset.
- Inspect the structure of the dataset.
- Identify missing values before cleaning.

In [62]:
import pandas as pd
import numpy as np

titanic = pd.read_csv("titanic.csv") 

print("========== First 5 Rows ==========")
print(titanic.head())

print("\n========== Dataset Information ==========")
titanic.info()

print("\n========== Missing Values ==========")
print(titanic.isnull())

print("\n========== Number of Missing Values ==========")
print(titanic.isnull().sum())

========== First 5 Rows ==========
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

========== Dataset Information ==========
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

========== Missing Values ==========
     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
886        False     False   False  False  False  False  False  False   False
887        False     False   False  False  False  False  False  False   False
888        False     False   False  False  False   True  False  False   False
889        False     False   False  False  False  False  False  False   False
890        False     False   False  False  False  False  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False  False     False
2    False   True     False
3    False  False     False
4    False   True     False
..     ...    ...       ...
886  False   True     False
887  False  False     False
888  False   True     False
889  False  False     False
890  False   True     False

[891 rows x 12 columns]

========== Number of Missing Values ==========
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Phase 2: Data Cleaning

## Objective
The dataset contains missing values.
In this phase, we will:
- Remove unnecessary columns.
- Fill missing values.
- Prepare the dataset for analysis.

In [63]:
print("========== Drop Cabin Column ==========")

titanic.drop("Cabin", axis=1, inplace=True) 
print('\n')

========== Drop Cabin Column ==========

In [64]:
print("========== Fill Missing Age ==========")

median_age = titanic["Age"].median()

titanic.fillna({"Age": median_age}, inplace=True)

========== Fill Missing Age ==========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [65]:
print("========== Fill Missing Embarked ==========")

titanic.fillna({"Embarked": "Unknown"}, inplace=True)

========== Fill Missing Embarked ==========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [66]:
print("========== Missing Values After Cleaning ==========")

print(titanic.isnull().sum())

========== Missing Values After Cleaning ==========
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

# Phase 3: Filtering and Hypothesis Testing

## Stakeholder Questions

The stakeholders want to know:

- Did gender affect survival?
- Did age affect survival?
- Did passenger class affect survival?
- How many passengers survived?

In [67]:
children = titanic[titanic["Age"] < 18]

print("Children")
print(children)

print("Total Children:", children.shape[0])

Children
     PassengerId  Survived  Pclass                                     Name  \
7              8         0       3           Palsson, Master. Gosta Leonard
9             10         1       2      Nasser, Mrs. Nicholas (Adele Achem)
10            11         1       3          Sandstrom, Miss. Marguerite Rut
14            15         0       3     Vestrom, Miss. Hulda Amanda Adolfina
16            17         0       3                     Rice, Master. Eugene
..           ...       ...     ...                                      ...
850          851         0       3  Andersson, Master. Sigvard Harald Elias
852          853         0       3                  Boulos, Miss. Nourelain
853          854         1       1                Lines, Miss. Mary Conover
869          870         1       3          Johnson, Master. Harold Theodor
875          876         1       3         Najib, Miss. Adele Kiamie "Jane"

        Sex   Age  SibSp  Parch    Ticket     Fare Embarked
7      male   2.0      3      1    349909  21.0750        S
9    female  14.0      1      0    237736  30.0708        C
10   female   4.0      1      1   PP 9549  16.7000        S
14   female  14.0      0      0    350406   7.8542        S
16     male   2.0      4      1    382652  29.1250        Q
..      ...   ...    ...    ...       ...      ...      ...
850    male   4.0      4      2    347082  31.2750        S
852  female   9.0      1      1      2678  15.2458        C
853  female  16.0      0      1  PC 17592  39.4000        S
869    male   4.0      1      1    347742  11.1333        S
875  female  15.0      0      0      2667   7.2250        C

[113 rows x 11 columns]
Total Children: 113

In [68]:
survival_rate = titanic["Survived"].mean() * 100

print("Overall Survival Rate")

print(f"{survival_rate:.2f}%")

Overall Survival Rate
38.38%

In [70]:
survived = titanic[titanic["Survived"] == 1]

print("Total Survived Passengers")

print(survived.shape[0])

Total Survived Passengers
342

In [71]:
survived_children = titanic[
    (titanic["Age"] < 18) &
    (titanic["Survived"] == 1)
]

print("Survived Children")

print(survived_children.shape[0])

Survived Children
61

In [72]:
survived_adults = titanic[
    (titanic["Age"] >= 18) &
    (titanic["Survived"] == 1)
]

print("Survived Adults")

print(survived_adults.shape[0])

Survived Adults
281

In [73]:
survived_class1 = titanic[
    (titanic["Pclass"] == 1) &
    (titanic["Survived"] == 1)
]

survived_class2 = titanic[
    (titanic["Pclass"] == 2) &
    (titanic["Survived"] == 1)
]

survived_class3 = titanic[
    (titanic["Pclass"] == 3) &
    (titanic["Survived"] == 1)
]

print("Class 1 Survivors:", survived_class1.shape[0])
print("Class 2 Survivors:", survived_class2.shape[0])
print("Class 3 Survivors:", survived_class3.shape[0])

Class 1 Survivors: 136
Class 2 Survivors: 87
Class 3 Survivors: 119

In [74]:
survived_male = titanic[
    (titanic["Sex"] == "male") &
    (titanic["Survived"] == 1)
]

survived_female = titanic[
    (titanic["Sex"] == "female") &
    (titanic["Survived"] == 1)
]

print("Male Survivors:", survived_male.shape[0])

print("Female Survivors:", survived_female.shape[0])

Male Survivors: 109
Female Survivors: 233

# Phase 4: GroupBy Analytics

## Objective

In this phase, we use the Split → Apply → Combine methodology to answer stakeholder questions.

We group passengers by:

- Gender
- Passenger Class
- Age Group

Then calculate:
- Total Passengers
- Survivors
- Survival Rate

In [75]:
gender = titanic.groupby("Sex").agg(
    Total_Passengers=("PassengerId", "count"),
    Survivors=("Survived", "sum"),
    Survival_Rate=("Survived", "mean")
)

gender["Survival_Rate"] = gender["Survival_Rate"] * 100

print(gender)

        Total_Passengers  Survivors  Survival_Rate
Sex
female               314        233      74.203822
male                 577        109      18.890815

In [76]:
pclass = titanic.groupby("Pclass").agg(
    Total_Passengers=("PassengerId", "count"),
    Survivors=("Survived", "sum"),
    Survival_Rate=("Survived", "mean")
)

pclass["Survival_Rate"] = pclass["Survival_Rate"] * 100

print(pclass)

        Total_Passengers  Survivors  Survival_Rate
Pclass
1                    216        136      62.962963
2                    184         87      47.282609
3                    491        119      24.236253

In [77]:
titanic["Age Group"] = np.where(
    titanic["Age"] < 18,
    "Child",
    "Adult"
)

age_group = titanic.groupby("Age Group").agg(
    Total_Passengers=("PassengerId", "count"),
    Survivors=("Survived", "sum"),
    Survival_Rate=("Survived", "mean")
)

age_group["Survival_Rate"] = age_group["Survival_Rate"] * 100

print(age_group)

           Total_Passengers  Survivors  Survival_Rate
Age Group
Adult                   778        281      36.118252
Child                   113         61      53.982301